name: 'Build revxlp10u - win'
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["xiao_ble"]'
      shield: '["revxlp"]'
      clipboard: '["win"]'
      kconfig: '["CONFIG_ZMK_USB=y\nCONFIG_ZMK_USB_LOGGING=y"]'
